[versions]
jooq = "3.18.7"
kotlin = "1.9.20"
gradle-publish = "1.2.1"


[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish"}

[libraries]
jooq-codegen = { module = "org.jooq:jooq-codegen", version.ref = "jooq" }