name: "PR Pipeline"

on:
  push:
    branches:
    - master
    - 'renovate/**'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  gradle-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, windows-2022, ubuntu-22.04]
    steps:
      - name: git clone
        uses: actions/checkout@v4.1.7
      - name: Set up JDKs
        uses: actions/setup-java@v4.3.0
        with:
          distribution: temurin
          java-version: |
            11
            17
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3.5.0
      - run: "./gradlew :check --continue"
