name: "Push Pipeline"

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
  workflow_dispatch:

jobs:
  gradle-build:
    runs-on: ubuntu-22.04
    steps:
      - name: git clone
        uses: actions/checkout@v4.1.7
      - name: Set up JDKs
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: |
            8
            11
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3.4.1
      - run: "./gradlew :test"