name: "Release pipeline"

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  version:
    name: Get version number from tag
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - name: Read version
        id: vars
        # extract tag name without v prefix
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash

  publish:
    needs: version
    name: Publish artifact to Gradle Plugins portal
    runs-on: ubuntu-22.04
    steps:
      - name: git clone
        uses: actions/checkout@v4.1.1
      - name: Set up JDKs
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 8
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3.3.0
      - run: "./gradlew :publishPlugin -PpluginVersion=${{ needs.version.outputs.version }}"
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

  readme:
    needs: [ version, publish ]
    name: Replace version in README.md
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "version \"[0-9]+.[0-9]+.[0-9]+\""
          replace: "version \"${{ needs.version.outputs.version }}\""
          include: "**README.md"
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update plugin version.
          branch: master